# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/consti10/Desktop/wifibroadcast

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/consti10/Desktop/wifibroadcast

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/consti10/Desktop/wifibroadcast/CMakeFiles /home/consti10/Desktop/wifibroadcast/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/consti10/Desktop/wifibroadcast/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wifibroadcast

# Build rule for target.
wifibroadcast: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wifibroadcast
.PHONY : wifibroadcast

# fast build rule for target.
wifibroadcast/fast:
	$(MAKE) -f CMakeFiles/wifibroadcast.dir/build.make CMakeFiles/wifibroadcast.dir/build
.PHONY : wifibroadcast/fast

#=============================================================================
# Target rules for targets named lol

# Build rule for target.
lol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lol
.PHONY : lol

# fast build rule for target.
lol/fast:
	$(MAKE) -f CMakeFiles/lol.dir/build.make CMakeFiles/lol.dir/build
.PHONY : lol/fast

#=============================================================================
# Target rules for targets named fec

# Build rule for target.
fec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fec
.PHONY : fec

# fast build rule for target.
fec/fast:
	$(MAKE) -f CMakeFiles/fec.dir/build.make CMakeFiles/fec.dir/build
.PHONY : fec/fast

#=============================================================================
# Target rules for targets named radiotap

# Build rule for target.
radiotap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 radiotap
.PHONY : radiotap

# fast build rule for target.
radiotap/fast:
	$(MAKE) -f CMakeFiles/radiotap.dir/build.make CMakeFiles/radiotap.dir/build
.PHONY : radiotap/fast

src/WBReceiver.o: src/WBReceiver.cpp.o

.PHONY : src/WBReceiver.o

# target to build an object file
src/WBReceiver.cpp.o:
	$(MAKE) -f CMakeFiles/wifibroadcast.dir/build.make CMakeFiles/wifibroadcast.dir/src/WBReceiver.cpp.o
.PHONY : src/WBReceiver.cpp.o

src/WBReceiver.i: src/WBReceiver.cpp.i

.PHONY : src/WBReceiver.i

# target to preprocess a source file
src/WBReceiver.cpp.i:
	$(MAKE) -f CMakeFiles/wifibroadcast.dir/build.make CMakeFiles/wifibroadcast.dir/src/WBReceiver.cpp.i
.PHONY : src/WBReceiver.cpp.i

src/WBReceiver.s: src/WBReceiver.cpp.s

.PHONY : src/WBReceiver.s

# target to generate assembly for a file
src/WBReceiver.cpp.s:
	$(MAKE) -f CMakeFiles/wifibroadcast.dir/build.make CMakeFiles/wifibroadcast.dir/src/WBReceiver.cpp.s
.PHONY : src/WBReceiver.cpp.s

src/WBTransmitter.o: src/WBTransmitter.cpp.o

.PHONY : src/WBTransmitter.o

# target to build an object file
src/WBTransmitter.cpp.o:
	$(MAKE) -f CMakeFiles/wifibroadcast.dir/build.make CMakeFiles/wifibroadcast.dir/src/WBTransmitter.cpp.o
.PHONY : src/WBTransmitter.cpp.o

src/WBTransmitter.i: src/WBTransmitter.cpp.i

.PHONY : src/WBTransmitter.i

# target to preprocess a source file
src/WBTransmitter.cpp.i:
	$(MAKE) -f CMakeFiles/wifibroadcast.dir/build.make CMakeFiles/wifibroadcast.dir/src/WBTransmitter.cpp.i
.PHONY : src/WBTransmitter.cpp.i

src/WBTransmitter.s: src/WBTransmitter.cpp.s

.PHONY : src/WBTransmitter.s

# target to generate assembly for a file
src/WBTransmitter.cpp.s:
	$(MAKE) -f CMakeFiles/wifibroadcast.dir/build.make CMakeFiles/wifibroadcast.dir/src/WBTransmitter.cpp.s
.PHONY : src/WBTransmitter.cpp.s

src/external/fec/fec.o: src/external/fec/fec.cpp.o

.PHONY : src/external/fec/fec.o

# target to build an object file
src/external/fec/fec.cpp.o:
	$(MAKE) -f CMakeFiles/fec.dir/build.make CMakeFiles/fec.dir/src/external/fec/fec.cpp.o
.PHONY : src/external/fec/fec.cpp.o

src/external/fec/fec.i: src/external/fec/fec.cpp.i

.PHONY : src/external/fec/fec.i

# target to preprocess a source file
src/external/fec/fec.cpp.i:
	$(MAKE) -f CMakeFiles/fec.dir/build.make CMakeFiles/fec.dir/src/external/fec/fec.cpp.i
.PHONY : src/external/fec/fec.cpp.i

src/external/fec/fec.s: src/external/fec/fec.cpp.s

.PHONY : src/external/fec/fec.s

# target to generate assembly for a file
src/external/fec/fec.cpp.s:
	$(MAKE) -f CMakeFiles/fec.dir/build.make CMakeFiles/fec.dir/src/external/fec/fec.cpp.s
.PHONY : src/external/fec/fec.cpp.s

src/external/radiotap/radiotap.o: src/external/radiotap/radiotap.c.o

.PHONY : src/external/radiotap/radiotap.o

# target to build an object file
src/external/radiotap/radiotap.c.o:
	$(MAKE) -f CMakeFiles/radiotap.dir/build.make CMakeFiles/radiotap.dir/src/external/radiotap/radiotap.c.o
.PHONY : src/external/radiotap/radiotap.c.o

src/external/radiotap/radiotap.i: src/external/radiotap/radiotap.c.i

.PHONY : src/external/radiotap/radiotap.i

# target to preprocess a source file
src/external/radiotap/radiotap.c.i:
	$(MAKE) -f CMakeFiles/radiotap.dir/build.make CMakeFiles/radiotap.dir/src/external/radiotap/radiotap.c.i
.PHONY : src/external/radiotap/radiotap.c.i

src/external/radiotap/radiotap.s: src/external/radiotap/radiotap.c.s

.PHONY : src/external/radiotap/radiotap.s

# target to generate assembly for a file
src/external/radiotap/radiotap.c.s:
	$(MAKE) -f CMakeFiles/radiotap.dir/build.make CMakeFiles/radiotap.dir/src/external/radiotap/radiotap.c.s
.PHONY : src/external/radiotap/radiotap.c.s

src/lol.o: src/lol.cpp.o

.PHONY : src/lol.o

# target to build an object file
src/lol.cpp.o:
	$(MAKE) -f CMakeFiles/lol.dir/build.make CMakeFiles/lol.dir/src/lol.cpp.o
.PHONY : src/lol.cpp.o

src/lol.i: src/lol.cpp.i

.PHONY : src/lol.i

# target to preprocess a source file
src/lol.cpp.i:
	$(MAKE) -f CMakeFiles/lol.dir/build.make CMakeFiles/lol.dir/src/lol.cpp.i
.PHONY : src/lol.cpp.i

src/lol.s: src/lol.cpp.s

.PHONY : src/lol.s

# target to generate assembly for a file
src/lol.cpp.s:
	$(MAKE) -f CMakeFiles/lol.dir/build.make CMakeFiles/lol.dir/src/lol.cpp.s
.PHONY : src/lol.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... wifibroadcast"
	@echo "... lol"
	@echo "... fec"
	@echo "... radiotap"
	@echo "... src/WBReceiver.o"
	@echo "... src/WBReceiver.i"
	@echo "... src/WBReceiver.s"
	@echo "... src/WBTransmitter.o"
	@echo "... src/WBTransmitter.i"
	@echo "... src/WBTransmitter.s"
	@echo "... src/external/fec/fec.o"
	@echo "... src/external/fec/fec.i"
	@echo "... src/external/fec/fec.s"
	@echo "... src/external/radiotap/radiotap.o"
	@echo "... src/external/radiotap/radiotap.i"
	@echo "... src/external/radiotap/radiotap.s"
	@echo "... src/lol.o"
	@echo "... src/lol.i"
	@echo "... src/lol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

